# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=256)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('id_number', models.CharField(max_length=256)),
                ('wages', models.IntegerField()),
                ('birth_date', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField()),
                ('contact', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('insurer', models.IntegerField(default=0, max_length=2)),
                ('note', models.TextField()),
                ('display', models.IntegerField(default=1, max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.position')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('user_id_number', models.CharField(max_length=256)),
                ('user_photo_name', models.CharField(max_length=256)),
            ],
        ),
    ]
