# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_number', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('entry', models.CharField(max_length=4096)),
                ('entry_img', models.CharField(max_length=256)),
            ],
        ),
    ]
