# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_entry',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
