# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160904_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id_number',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
