# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160906_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='age',
        ),
    ]
